# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4dd405eb352ed9ddf11dcd979304b9d0a15daa83abe295711cb99e4643c3aac1e5823b105d51a5f6e7aff8621f38b67523d0fd0bcb5c440316cb6dc01d43d4

test:
  secret_key_base: f8366dcad75d264be20f681e2b05b57e764bfcb2331e29967c43e521559d3b2e49c0a8c73edc3d10139ed2fdd823678909b86ad64938d0f4d8d8019e39fa8fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
